export const ourProducts = [
  {
    id: 1,
    image: "image2/pro4.png",
    name: "HAVIT HV-G92 Gamepad",
    price: 100,
    stars: 3.4,
    reviews: 60,
  },
  {
    id: 2,
    image: "image2/pro3.png",
    name: "AK-900 Wired Keyboard",
    price: 360,
    stars: 4,
    reviews: 50,
  },
  {
    id: 3,
    image: "image2/pro2.png",
    name: "IPS LCD Gaming Monitor",
    price: 700,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 4,
    image: "image2/pro1.png",
    name: "S-Series Comfort Chair ",
    price: 500,
    stars: 2.1,
    reviews: 55,
  },
];

export const newProducts = [
  {
    id: 1,
    image: "image2/new1.png",
    sale: "New",
    name: "Kids Electric Car",
    price: 120,
    stars: 4.4,
    reviews: 60,
    input1: "num1",
    input2: "num2",
  },
  {
    id: 2,
    image: "image2/new2.png",
    sale: "New",
    name: "Jr. Zoom Soccer Cleats",
    price: 960,
    stars: 4,
    reviews: 50,
    input1: "num3",
    input2: "num4",
  },
  {
    id: 3,
    image: "image2/new3.png",
    sale: "New",
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    stars: 3.4,
    reviews: 40,
    input1: "num5",
    input2: "num6",
  },
  {
    id: 4,
    image: "image2/new4.png",
    sale: "New",
    name: "Quilted Satin Jacket",
    price: 660,
    stars: 4.1,
    reviews: 55,
    input1: "num7",
    input2: "num8",
  },
];
