export const BestProducts = [
  {
    id: 1,
    image: "image2/best1.png",
    sale: 40,
    name: "The north coat",
    price: 260,
    prastprice: 360,
    stars: 4.4,
    reviews: 65,
  },
  {
    id: 2,
    image: "image2/best2.png",
    sale: 35,
    name: "Gucci duffle bag",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 3,
    image: "image2/best3.png",
    sale: 30,
    name: "Gucci duffle bag",
    price: 160,
    prastprice: 170,
    stars: 3.4,
    reviews: 65,
  },
  {
    id: 4,
    image: "image2/best4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 360,
    prastprice: 500,
    stars: 4.1,
    reviews: 55,
  },
];
