export const viewAllProducts = [
  {
    id: 1,
    image: "image2/pro4.png",
    name: "HAVIT HV-G92 Gamepad",
    price: 100,
    stars: 3.4,
    reviews: 60,
  },
  {
    id: 2,
    image: "image2/pro3.png",
    name: "AK-900 Wired Keyboard",
    price: 360,
    stars: 4,
    reviews: 50,
  },
  {
    id: 3,
    image: "image2/pro2.png",
    name: "IPS LCD Gaming Monitor",
    price: 700,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 4,
    image: "image2/pro1.png",
    name: "S-Series Comfort Chair ",
    price: 500,
    stars: 2.1,
    reviews: 55,
  },
  {
    id: 5,
    image: "image2/new1.png",
    sale: "New",
    name: "Kids Electric Car",
    price: 120,
    stars: 4.4,
    reviews: 60,
    input1: "num1",
    input2: "num2",
  },
  {
    id: 6,
    image: "image2/new2.png",
    sale: "New",
    name: "Jr. Zoom Soccer Cleats",
    price: 960,
    stars: 4,
    reviews: 50,
    input1: "num3",
    input2: "num4",
  },
  {
    id: 7,
    image: "image2/new3.png",
    sale: "New",
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    stars: 3.4,
    reviews: 40,
    input1: "num5",
    input2: "num6",
  },
  {
    id: 8,
    image: "image2/new4.png",
    sale: "New",
    name: "Quilted Satin Jacket",
    price: 660,
    stars: 4.1,
    reviews: 55,
    input1: "num7",
    input2: "num8",
  },
  {
    id: 9,
    image: "image2/best1.png",
    sale: 40,
    name: "The north coat",
    price: 260,
    prastprice: 360,
    stars: 4.4,
    reviews: 65,
  },
  {
    id: 10,
    image: "image2/best2.png",
    sale: 35,
    name: "Gucci duffle bag",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 11,
    image: "image2/best3.png",
    sale: 30,
    name: "Gucci duffle bag",
    price: 160,
    prastprice: 170,
    stars: 3.4,
    reviews: 65,
  },
  {
    id: 12,
    image: "image2/best4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 360,
    prastprice: 500,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 13,
    image: "image2/cart1.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 4.4,
    reviews: 60,
  },
  {
    id: 14,
    image: "image2/cart2.png",
    sale: 35,
    name: "AK-900 Wired Keyboard",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 15,
    image: "image2/cart3.png",
    sale: 30,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    prastprice: 400,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 16,
    image: "image2/cart4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 375,
    prastprice: 400,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 17,
    image: "image2/cart4.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 3.8,
    reviews: 65,
  },
  {
    id: 18,
    image: "image2/cart1.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 4.4,
    reviews: 60,
  },
  {
    id: 19,
    image: "image2/cart2.png",
    sale: 35,
    name: "AK-900 Wired Keyboard",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 20,
    image: "image2/cart3.png",
    sale: 30,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    prastprice: 400,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 21,
    image: "image2/cart4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 375,
    prastprice: 400,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 22,
    image: "image2/cart4.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 3.8,
    reviews: 65,
  },
  {
    id: 23,
    image: "image2/cart1.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 4.4,
    reviews: 60,
  },
  {
    id: 24,
    image: "image2/cart2.png",
    sale: 35,
    name: "AK-900 Wired Keyboard",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 25,
    image: "image2/cart3.png",
    sale: 30,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    prastprice: 400,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 26,
    image: "image2/cart4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 375,
    prastprice: 400,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 27,
    image: "image2/cart4.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 3.8,
    reviews: 65,
  },
];
