export const carts = [
  {
    id: 1,
    image: "image2/cart1.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 4.4,
    reviews: 60,
  },
  {
    id: 2,
    image: "image2/cart2.png",
    sale: 35,
    name: "AK-900 Wired Keyboard",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 3,
    image: "image2/cart3.png",
    sale: 30,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    prastprice: 400,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 4,
    image: "image2/cart4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 375,
    prastprice: 400,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 5,
    image: "image2/cart4.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 3.8,
    reviews: 65,
  },
  {
    id: 6,
    image: "image2/cart1.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 4.4,
    reviews: 60,
  },
  {
    id: 7,
    image: "image2/cart2.png",
    sale: 35,
    name: "AK-900 Wired Keyboard",
    price: 960,
    prastprice: 1160,
    stars: 4,
    reviews: 50,
  },
  {
    id: 8,
    image: "image2/cart3.png",
    sale: 30,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    prastprice: 400,
    stars: 3.4,
    reviews: 40,
  },
  {
    id: 9,
    image: "image2/cart4.png",
    sale: 25,
    name: "S-Series Comfort Chair ",
    price: 375,
    prastprice: 400,
    stars: 4.1,
    reviews: 55,
  },
  {
    id: 10,
    image: "image2/cart4.png",
    sale: 40,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    prastprice: 160,
    stars: 3.8,
    reviews: 65,
  },
];
